### ISSUE TITLE
文件树无法打开

### ISSUE THREAD

**Issue by a674709300** [Martins3/My-Linux-Config#43]
安装后遇到些问题
系统是 manjaro
以前按 2020 年那篇安装的时候，是可以正常使用的。最近更新重装了下，就出问题了，目前主要是这两个问题

F3 无法显示文件树，提示： 
E492:Not an editor command: NvimTreeToggle

<Space> f s 无法保存，提示：
E5108:Error executing lua [string ":lua"]:1: attempt to index global 'myluamodule' (a nil value)
stack traceback:
      [string ":lua"]:1: in main chunk

**Comment by a674709300** [comment]
ccls --version

ccls version <unknown>
clang version 13.0.0


nvim --version

NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
编译者 builduser

Features: +acl +iconv +tui
See ":help feature-compile"

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/usr/share/nvim"

Run :checkhealth for more info

**Comment by a674709300** [comment]
custom_plugins = 
[
  ['neoclide/coc.nvim', {'rev': 'release', 'name': 'neoclide/coc.nvim', 'merge': 0, 'overwrite': 1}], 
  ['antoinemadec/coc-fzf', {'name': 'antoinemadec/coc-fzf', 'branch': 'release', 'overwrite': 1}], 
  ['junegunn/fzf.vim', {'name': 'junegunn/fzf.vim', 'overwrite': 1}], 
  ['dhruvasagar/vim-table-mode', {'name': 'dhruvasagar/vim-table-mode', 'overwrite': 1}], 
  ['liuchengxu/vista.vim', {'name': 'liuchengxu/vista.vim', 'overwrite': 1}], 
  ['simeji/winresizer', {'name': 'simeji/winresizer', 'overwrite': 1}], 
  ['jackguo380/vim-lsp-cxx-highlight', {'name': 'jackguo380/vim-lsp-cxx-highlight', 'overwrite': 1}], 
  ['skywind3000/vim-cppman', {'name': 'skywind3000/vim-cppman', 'overwrite': 1}], 
  ['rhysd/git-messenger.vim', {'lazy': 1, 'name': 'rhysd/git-messenger.vim', 'on_cmd': 'GitMessenger', 'overwrite': 1}], 
  ['voldikss/vim-floaterm',{'name': 'voldikss/vim-floaterm', 'overwrite': 1}], 
  ['google/vim-searchindex.git', {'name': 'google/vim-searchindex.git', 'overwrite': 1}], 
  ['honza/vim-snippets', {'name': 'honza/vim-snippets', 'overwrite': 1}],
  ['nvim-lua/plenary.nvim', {'name': 'nvim-lua/plenary.nvim', 'overwrite': 1}], 
  ['nvim-telescope/telescope.nvim', {'name': 'nvim-telescope/telescope.nvim', 'overwrite': 1}], 
  ['fannheyward/telescope-coc.nvim', {'name': 'fannheyward/telescope-coc.nvim', 'overwrite': 1}], 
  ['nvim-telescope/telescope-fzf-native.nvim', {'build': 'make', 'name': 'nvim-telescope/telescope-fzf-native.nvim', 'overwrite': 1}],  
  ['nvim-treesitter/nvim-treesitter', {'name': 'nvim-treesitter/nvim-treesitter', 'overwrite': 1}], 
  ['kyazdani42/nvim-web-devicons', {'name': 'kyazdani42/nvim-web-devicons', 'overwrite': 1}], 
  ['MunifTanjim/nui.nvim', {'name': 'MunifTanjim/nui.nvim', 'overwrite': 1}], 
  ['rcarriga/nvim-notify', {'name': 'rcarriga/nvim-notify', 'overwrite': 1}], 
  ['kyazdani42/nvim-tree.lua', {'name': 'kyazdani42/nvim-tree.lua', 'overwrite': 1}]
]

**Comment by a674709300** [comment]
### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'coc'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['neoclide/coc.nvim', {'rev': 'release', 'name': 'neoclide/coc.nvim', 'merge': 0, 'overwrite': 1}], ['antoinemadec/coc-fzf', {'name': 'antoinemadec/coc-fzf', 'branch': 'release', 'overwrite':
 1}], ['junegunn/fzf.vim', {'name': 'junegunn/fzf.vim', 'overwrite': 1}], ['dhruvasagar/vim-table-mode', {'name': 'dhruvasagar/vim-table-mode', 'overwrite': 1}], ['liuchengxu/vista.vim', {'name': 'liuchengxu/vis
ta.vim', 'overwrite': 1}], ['simeji/winresizer', {'name': 'simeji/winresizer', 'overwrite': 1}], ['jackguo380/vim-lsp-cxx-highlight', {'name': 'jackguo380/vim-lsp-cxx-highlight', 'overwrite': 1}], ['skywind3000/
vim-cppman', {'name': 'skywind3000/vim-cppman', 'overwrite': 1}], ['rhysd/git-messenger.vim', {'lazy': 1, 'name': 'rhysd/git-messenger.vim', 'on_cmd': 'GitMessenger', 'overwrite': 1}], ['voldikss/vim-floaterm',
{'name': 'voldikss/vim-floaterm', 'overwrite': 1}], ['google/vim-searchindex.git', {'name': 'google/vim-searchindex.git', 'overwrite': 1}], ['honza/vim-snippets', {'name': 'honza/vim-snippets', 'overwrite': 1}],
 ['nvim-lua/plenary.nvim', {'name': 'nvim-lua/plenary.nvim', 'overwrite': 1}], ['nvim-telescope/telescope.nvim', {'name': 'nvim-telescope/telescope.nvim', 'overwrite': 1}], ['fannheyward/telescope-coc.nvim', {'n
ame': 'fannheyward/telescope-coc.nvim', 'overwrite': 1}], ['nvim-telescope/telescope-fzf-native.nvim', {'build': 'make', 'name': 'nvim-telescope/telescope-fzf-native.nvim', 'overwrite': 1}], ['nvim-treesitter/nv
im-treesitter', {'name': 'nvim-treesitter/nvim-treesitter', 'overwrite': 1}], ['kyazdani42/nvim-web-devicons', {'name': 'kyazdani42/nvim-web-devicons', 'overwrite': 1}], ['MunifTanjim/nui.nvim', {'name': 'MunifT
anjim/nui.nvim', 'overwrite': 1}], ['rcarriga/nvim-notify', {'name': 'rcarriga/nvim-notify', 'overwrite': 1}], ['kyazdani42/nvim-tree.lua', {'name': 'kyazdani42/nvim-tree.lua', 'overwrite': 1}]]
  data_dir = '/home/alioth/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = ['indent-blankline.nvim']
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 0
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/alioth/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vimtex'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'bar'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '2.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 'c'
  windows_smartclose = 'q'
  wrap_line = 0
```


### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="tools"
[[layers]]
  name="VersionControl"
  enable-gtm-status=1
[[layers]]
  name="git"
  git-plugin='fugitive'
[[layers]]
  name="fzf"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#latex"
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :
```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [15:53:38] [0.000] [  Info ] Loading SpaceVim from: /home/alioth/.SpaceVim/
[ SpaceVim ] [15:53:38] [0.120] [  Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [15:53:38] [0.133] [  Info ] find local conf: /home/alioth/.SpaceVim.d/init.toml
[ SpaceVim ] [15:53:38] [0.134] [  Info ] loading cached local conf: /home/alioth/.cache/SpaceVim/conf/_home_alioth__SpaceVim_d_init_toml.json
[ SpaceVim ] [15:53:38] [0.134] [  Info ] start to apply config [local]
[ SpaceVim ] [15:53:38] [0.147] [  Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [15:53:38] [0.276] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [15:53:38] [0.276] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [15:53:39] [0.363] [  Info ] finished loading SpaceVim!
[ SpaceVim ] [15:53:39] [0.525] [  Info ] try to open SpaceVim welcome page
[   rooter ] [15:53:39] [0.547] [  Info ] Load projects cache from: /home/alioth/.cache/SpaceVim/projects.json
```
</details>




custom_plugins = 
[
  ['neoclide/coc.nvim', {'rev': 'release', 'name': 'neoclide/coc.nvim', 'merge': 0, 'overwrite': 1}], 
  ['antoinemadec/coc-fzf', {'name': 'antoinemadec/coc-fzf', 'branch': 'release', 'overwrite': 1}], 
  ['junegunn/fzf.vim', {'name': 'junegunn/fzf.vim', 'overwrite': 1}], 
  ['dhruvasagar/vim-table-mode', {'name': 'dhruvasagar/vim-table-mode', 'overwrite': 1}], 
  ['liuchengxu/vista.vim', {'name': 'liuchengxu/vista.vim', 'overwrite': 1}], 
  ['simeji/winresizer', {'name': 'simeji/winresizer', 'overwrite': 1}], 
  ['jackguo380/vim-lsp-cxx-highlight', {'name': 'jackguo380/vim-lsp-cxx-highlight', 'overwrite': 1}], 
  ['skywind3000/vim-cppman', {'name': 'skywind3000/vim-cppman', 'overwrite': 1}], 
  ['rhysd/git-messenger.vim', {'lazy': 1, 'name': 'rhysd/git-messenger.vim', 'on_cmd': 'GitMessenger', 'overwrite': 1}], 
  ['voldikss/vim-floaterm',{'name': 'voldikss/vim-floaterm', 'overwrite': 1}], 
  ['google/vim-searchindex.git', {'name': 'google/vim-searchindex.git', 'overwrite': 1}], 
  ['honza/vim-snippets', {'name': 'honza/vim-snippets', 'overwrite': 1}],
  ['nvim-lua/plenary.nvim', {'name': 'nvim-lua/plenary.nvim', 'overwrite': 1}], 
  ['nvim-telescope/telescope.nvim', {'name': 'nvim-telescope/telescope.nvim', 'overwrite': 1}], 
  ['fannheyward/telescope-coc.nvim', {'name': 'fannheyward/telescope-coc.nvim', 'overwrite': 1}], 
  ['nvim-telescope/telescope-fzf-native.nvim', {'build': 'make', 'name': 'nvim-telescope/telescope-fzf-native.nvim', 'overwrite': 1}],  
  ['nvim-treesitter/nvim-treesitter', {'name': 'nvim-treesitter/nvim-treesitter', 'overwrite': 1}], 
  ['kyazdani42/nvim-web-devicons', {'name': 'kyazdani42/nvim-web-devicons', 'overwrite': 1}], 
  ['MunifTanjim/nui.nvim', {'name': 'MunifTanjim/nui.nvim', 'overwrite': 1}], 
  ['rcarriga/nvim-notify', {'name': 'rcarriga/nvim-notify', 'overwrite': 1}], 
  ['kyazdani42/nvim-tree.lua', {'name': 'kyazdani42/nvim-tree.lua', 'overwrite': 1}]
]

**Comment by a674709300** [comment]
coc: health#coc#check
========================================================================
  - OK: Environment check passed
  - OK: Javascript bundle build/index.js found
  - OK: Service started

coc_fzf: health#coc_fzf#check
========================================================================
## ctags (optional)
  - OK: ctag found

## fzf.vim (optional)
  - OK: fzf.vim found

floaterm: health#floaterm#check
========================================================================
## common
  - INFO: Platform: linux
  - INFO: Nvim: NVIM v0.6.1
  - INFO: Plugin: fatal: not a git repository (or any of the parent directories): .git


## terminal
  - OK: Terminal emulator is available

## floating
  - OK: Floating window is available

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.2 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.3.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpd

**Comment by a674709300** [comment]
## versions

vim version: NVIM v0.6.1
node version: v17.3.0
coc.nvim version: 0.0.80-0428328f9a
coc.nvim directory: /home/alioth/.cache/vimfiles/repos/github.com/neoclide/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2022-01-29T15:53:39.397 WARN (pid:13409) [attach] - Plugin not ready when received "registNotification" [ 'cquery', '$cquery/publishSemanticHighlighting' ]
2022-01-29T15:53:39.399 WARN (pid:13409) [attach] - Plugin not ready when received "registNotification" [ 'cquery', '$cquery/setInactiveRegions' ]
2022-01-29T15:53:39.399 WARN (pid:13409) [attach] - Plugin not ready when received "registNotification" [ 'ccls', '$ccls/publishSemanticHighlight' ]
2022-01-29T15:53:39.399 WARN (pid:13409) [attach] - Plugin not ready when received "registNotification" [ 'ccls', '$ccls/publishSkippedRanges' ]
2022-01-29T15:53:39.550 INFO (pid:13409) [services] - registered service "languageserver.ccls"
2022-01-29T15:53:40.094 INFO (pid:13409) [services] - registered service "diagnostic-languageserver"
2022-01-29T15:53:40.269 INFO (pid:13409) [coc-git] - Looking for git in: git
2022-01-29T15:53:40.330 INFO (pid:13409) [plugin] - coc.nvim initialized with node: v17.3.0 after 920ms
2022-01-29T15:53:40.334 INFO (pid:13409) [attach] - receive notification: highlight []
2022-01-29T15:53:40.334 INFO (pid:13409) [attach] - receive notification: registNotification [ 'cquery', '$cquery/publishSemanticHighlighting' ]
2022-01-29T15:53:40.335 INFO (pid:13409) [attach] - receive notification: registNotification [ 'cquery', '$cquery/setInactiveRegions' ]
2022-01-29T15:53:40.335 INFO (pid:13409) [attach] - receive notification: registNotification [ 'ccls', '$ccls/publishSemanticHighlight' ]
2022-01-29T15:53:40.335 INFO (pid:13409) [attach] - receive notification: registNotification [ 'ccls', '$ccls/publishSkippedRanges' ]
2022-01-29T15:57:17.411 INFO (pid:13409) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'TabEnter',
  1
]
2022-01-29T15:57:25.190 INFO (pid:13409) [attach] - receive notification: highlight []
2022-01-29T15:57:27.361 INFO (pid:13409) [attach] - receive notification: highlight []
2022-01-29T15:57:37.160 INFO (pid:13409) [attach] - receive notification: highlight []
2022-01-29T15:57:59.176 INFO (pid:13409) [attach] - receive notification: highlight []
2022-01-29T15:58:15.057 INFO (pid:13409) [attach] - receive notification: highlight []
2022-01-29T15:58:15.498 INFO (pid:13409) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'TabEnter',
  1
]
2022-01-29T15:58:16.138 INFO (pid:13409) [attach] - receive notification: highlight []
2022-01-29T15:58:39.456 INFO (pid:13409) [attach] - receive notification: highlight []
2022-01-29T15:58:40.576 INFO (pid:13409) [attach] - receive notification: showInfo []

**Comment by Martins3** [comment]
因为前一段时间试图让龙芯上使用我这一套配置[^1]，折腾了很长时间，由于操作失误，一些尝试性的代码直接被 push 到 master 上了，给你带来了困扰，很抱歉，之后我设置分支管理策略，禁止直接 push 到 master 分支避免类似的问题。

我会最近一两天更新一下代码和文档，如果你着急使用，可以 checkout 到 6c3a733606a0ad01d807415b246f630098370497 上。

[^1]: https://github.com/Martins3/Martins3.github.io/blob/master/docs/loongarch/neovim.md

**Comment by a674709300** [comment]
好的，这套配置用着很顺手，几乎都不用我在折腾了，非常感谢 ：）

**Comment by Datebasesystem** [comment]
应该搞个tag之类的，这个问题困扰了我很久：）

**Comment by Martins3** [comment]
> 应该搞个tag之类的，这个问题困扰了我很久：）

嗯嗯，有道理

**Comment by Martins3** [comment]
[在 dev 分支上](https://github.com/Martins3/My-Linux-Config/tree/dev) 中将代码重构了一下，但是 #44 的问题实际上没有被解决，这个问题已经被提交给 orgmode 的作者了，如果解决了，差不多就可以 merge 到 master 上了。

**Comment by Martins3** [comment]
https://github.com/Shougo/dein.vim/issues/441 修复了 #44 但是 spacevim 直接包含了
https://github.com/SpaceVim/SpaceVim/tree/master/bundle/dein.vim，导致暂时这个问题还是无法被修复，暂时可以删除 orgmode  这个插件维持一下生活。

**Comment by a674709300** [comment]
现在还是拉是主干分支吗，
我这边拉的主干，
运行 nvim，提示：bootstrap_after function failed to execute. Check 'SPC h L' for errors。
然后 F3 还是无法显示文件树，还是提示：E492:Not an editor command: NvimTreeToggle
是 lua 相关的的东西问题吗



```
SPDebugInfo
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'coc'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['neoclide/coc.nvim', {'rev': 'release', 'name': 'neoclide/coc.nvim', 'merge': 0, 'overwrite': 1}], ['dhruvasagar/vim-table-mode', {'name': 'dhruvasagar/vim-table-mode', 'overwrite': 1}], ['l
iuchengxu/vista.vim', {'name': 'liuchengxu/vista.vim', 'overwrite': 1}], ['simeji/winresizer', {'name': 'simeji/winresizer', 'overwrite': 1}], ['jackguo380/vim-lsp-cxx-highlight', {'name': 'jackguo380/vim-lsp-cx
x-highlight', 'overwrite': 1}], ['skywind3000/vim-cppman', {'name': 'skywind3000/vim-cppman', 'overwrite': 1}], ['rhysd/git-messenger.vim', {'lazy': 1, 'name': 'rhysd/git-messenger.vim', 'on_cmd': 'GitMessenger'
, 'overwrite': 1}], ['voldikss/vim-floaterm', {'name': 'voldikss/vim-floaterm', 'overwrite': 1}], ['google/vim-searchindex.git', {'name': 'google/vim-searchindex.git', 'overwrite': 1}], ['honza/vim-snippets', {'
name': 'honza/vim-snippets', 'overwrite': 1}], ['nvim-lua/plenary.nvim', {'name': 'nvim-lua/plenary.nvim', 'overwrite': 1}], ['nvim-telescope/telescope.nvim', {'name': 'nvim-telescope/telescope.nvim', 'overwrite
': 1}], ['fannheyward/telescope-coc.nvim', {'name': 'fannheyward/telescope-coc.nvim', 'overwrite': 1}], ['nvim-telescope/telescope-fzf-native.nvim', {'build': 'make', 'name': 'nvim-telescope/telescope-fzf-native
.nvim', 'overwrite': 1}], ['nvim-treesitter/nvim-treesitter', {'name': 'nvim-treesitter/nvim-treesitter', 'overwrite': 1}], ['kyazdani42/nvim-tree.lua', {'name': 'kyazdani42/nvim-tree.lua', 'overwrite': 1}], ['k
yazdani42/nvim-web-devicons', {'name': 'kyazdani42/nvim-web-devicons', 'overwrite': 1}], ['pwntester/octo.nvim', {'name': 'pwntester/octo.nvim', 'overwrite': 1}], ['CoatiSoftware/vim-sourcetrail', {'name': 'Coat
iSoftware/vim-sourcetrail', 'overwrite': 1}], ['Martins3/refresh.nvim', {'name': 'Martins3/refresh.nvim', 'overwrite': 1}], ['nvim-orgmode/orgmode', {'name': 'nvim-orgmode/orgmode', 'overwrite': 1}], ['rcarriga/
nvim-notify', {'name': 'rcarriga/nvim-notify', 'overwrite': 1}], ['wakatime/vim-wakatime', {'name': 'wakatime/vim-wakatime', 'overwrite': 1}], ['MunifTanjim/nui.nvim', {'name': 'MunifTanjim/nui.nvim', 'overwrite
': 1}]]
  data_dir = '/home/alioth/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = ['indent-blankline.nvim']
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 0
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/alioth/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vimtex'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'bar'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '2.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 'c'
  windows_smartclose = 'q'
  wrap_line = 0
```


### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="tools"
[[layers]]
  name="VersionControl"
  enable-gtm-status=1
[[layers]]
  name="git"
  git-plugin='fugitive'
[[layers]]
  name="fzf"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#latex"
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [15:11:44] [0.001] [  Info ] Loading SpaceVim from: /home/alioth/.SpaceVim/
[ SpaceVim ] [15:11:44] [0.134] [  Info ] Startup with no argv, current dir is used: ~/.SpaceVim.d/autoload
[ SpaceVim ] [15:11:44] [0.143] [  Info ] start loading global config >>>
[ SpaceVim ] [15:11:44] [0.144] [  Info ] global_dir is: /home/alioth/.SpaceVim.d/
[ SpaceVim ] [15:11:44] [0.144] [  Info ] start to apply config [glob]
[ SpaceVim ] [15:11:44] [0.149] [  Info ] Could not find project local config
[ SpaceVim ] [15:11:44] [0.157] [  Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [15:11:44] [0.292] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [15:11:44] [0.292] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [15:11:44] [0.384] [  Info ] finished loading SpaceVim!
[ SpaceVim ] [15:11:44] [0.613] [  Info ] try to open SpaceVim welcome page
[   rooter ] [15:11:44] [0.659] [  Info ] Load projects cache from: /home/alioth/.cache/SpaceVim/projects.json
[ SpaceVim ] [15:11:44] [0.666] [ Error ] failed to call bootstrap_after function: myspacevim#after
[ SpaceVim ] [15:11:44] [0.666] [ Error ]        exception: Vim(lua):E5108: Error executing lua /home/alioth/.SpaceVim.d//lua/orgmode-config.lua:21: module 'orgmode' not found:
        no field package.preload['orgmode']
        no file './orgmode.lua'
        no file '/usr/share/luajit-2.0.5/orgmode.lua'
        no file '/usr/local/share/lua/5.1/orgmode.lua'
        no file '/usr/local/share/lua/5.1/orgmode/init.lua'
        no file '/usr/share/lua/5.1/orgmode.lua'
        no file '/usr/share/lua/5.1/orgmode/init.lua'
        no file '../lua/orgmode.lua'
        no file './orgmode.so'
        no file './orgmode.so'                     
        no file '/usr/local/lib/lua/5.1/orgmo
        no file '/usr/lib/lua/5.1/orgmode.so'      
        no file 
stack traceback:                  
        [C]: in function 'require'                                        
        /home/alioth/.SpaceVim.d//
        [C]: in function 'require'      
        [string ":lua"]:1: in main chunk                                                                                       
[ S
```       
```
